name: Mod Test Runner
run-name: ${{ github.actor }} is running mod unit tests ğŸ¤–
on:
  release:
  pull_request:
  push:
    branches:
      - main
      - integration/**
jobs:
  FCF-regression:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  GPS-unit-test:
    needs: FCF-regression
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Install test environment
        run: |
          python -m pip install --upgrade pip
          pip install gcovr
      - name: Check out FCF repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware
          repository: SunDevilRocketry/Flight-Computer-Firmware.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The flight-computer-firmware repository has been cloned to the runner."
      - name: Check out test repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware/test
          repository: SunDevilRocketry/test.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The test repository has been cloned to the runner."
      - name: Check out mod repository code
        uses: actions/checkout@v4
        with:
          path: Flight-Computer-Firmware/mod
          submodules: 'true'
      - run: echo "ğŸ’¡ The mod repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Build and run the GPS tests
        run: |
          cd Flight-Computer-Firmware/test/mod/gps
          make test
      - run: mv Flight-Computer-Firmware/test/mod/gps/results.txt Flight-Computer-Firmware/test/mod/gps/coverage/results.txt
      - name: "Promote Artifacts"
        uses: actions/upload-artifact@v4
        id: promote-results
        with:
          name: gps-artifacts
          path: Flight-Computer-Firmware/test/mod/gps/coverage/
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.promote-results.outputs.artifact-id }}'
      
      - run: echo "ğŸ This job's status is ${{ job.status }}."