name: Mod Test Runner
run-name: ${{ github.actor }} is running mod unit tests ğŸ¤–
on:
  release:
  pull_request:
  push:
    branches:
      - main
      - integration/**
jobs:
  FCF-regression:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: SunDevilRocketry/Flight-Computer-Firmware.git
          submodules: 'true'
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build and run the GPS tests
        run: |
          cd test/mod/gps
          make
          make test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  GPS-unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}."
      - name: Check out FCF repository code
        uses: actions/checkout@v4
        with:
          repository: SunDevilRocketry/Flight-Computer-Firmware.git
          ref: main
          submodules: 'true'
      - run: cd Flight-Computer-Firmware
      - run: echo "ğŸ’¡ The flight-computer-firmware repository has been cloned to the runner."
      - name: Check out test repository code
        uses: actions/checkout@v4
        with:
          repository: SunDevilRocketry/test.git
          ref: main
          submodules: 'true'
      - run: echo "ğŸ’¡ The test repository has been cloned to the runner."
      - name: Check out mod repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: echo "ğŸ’¡ The mod repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build and run the GPS tests
        run: |
          cd test/mod/gps
          make test
      - run: echo "ğŸ This job's status is ${{ job.status }}."